#!/bin/bash
# Clear the Terminal log screen.
clear
# Set build version
VERSION="r2"
# Remove old modules and old zImage.
rm kernel-pack/system/lib/modules/bcmdhd.ko
rm kernel-pack/kernel/zImage
# Copy new modules and new zImage.
cp drivers/net/wireless/bcmdhd/bcmdhd.ko kernel-pack/system/lib/modules
cp drivers/net/kineto_gan.ko kernel-pack/system/lib/modules
cp arch/arm/boot/zImage kernel-pack/kernel
# Creat a zip package.
cd kernel-pack
zip -r ask-vision-$VERSION.zip *
# Drop it to releasing folder
mv ask-vision-$VERSION.zip .../fixme/please
# FIXME: correct the location of 'releasing folder'.
